name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        sudo pip install strato-skipper
        mkdir -p ~/.docker
        echo "{}" > ~/.docker/config.json
        touch ${HOME}/.gitconfig
    - name: build
      run: |
        skipper make
    - name: Get release version
      id: get_version
      run: echo ::set-env name=GIT_REVISION::$(echo ${GITHUB_SHA})
    - name: Publish to Registry
      # Publish the image only in case of push to master
      if: github.event_name != 'pull_request'
      uses: elgohr/Publish-Docker-Github-Action@2.15
      with:
        name: assisted-installer
        username: ${{ secrets.OCPMETAL_USERNAME }}
        password: ${{ secrets.OCPMETAL_PASSWORD }}
        REGISTRY: 'quay.io/ocpmetal'
        dockerfile: Dockerfile.assisted-installer
        buildargs: GIT_REVISION
        tags: "stable,${{ env.GIT_REVISION }}"
